fix(encoding/toml): throws parse error when toml uses invalid whitespaces
denoland/deno_std pull request #1013
Opened 2021-07-08 12:44 UTC by FujiHaruka

According to [TOML spec](https://github.com/toml-lang/toml.io/blob/main/specs/en/v1.0.0.md#spec), whitespace means tab (0x09) or space (0x20).

Current TOML parser uses `Strong.prototype.trim()` to trim whitespaces, but it trims invalid whitespaces (for example, `\u3000`).

To fix it, I defined custom `trim` function and make the parser use it.

2021-07-08 12:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=1013) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=1013) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=1013) it.</sub>

2021-07-08 14:01 UTC, wperron requested changes

2021-07-09 11:45 UTC, FujiHaruka commented on encoding/toml.ts
> +    .replace(/[ \t]*$/, "");
@wperron 
I've added a test case to test the function.
And I also improved error message to escape white spaces like `\u3000`.
How do you like it?

2021-07-09 13:15 UTC, wperron approved these changes
Looking good, thanks for the contribution!

2021-07-09 13:26 UTC, merged