feat(node): worker_threads
denoland/deno_std pull request #1151
Opened 2021-08-22 19:11 UTC by Mesteery

2021-08-22 19:15 UTC, Mesteery commented
CI errors are related to https://github.com/denoland/deno/issues/9696.

2021-08-23 12:26 UTC, bartlomieju requested changes
This looks good @Mesteery, but please some more tests that actually execute some code in workers.

2021-08-23 16:10 UTC, Mesteery commented
Yes of course, the more complete tests are already added locally.
The problem is that it's not completely ready, since the implementation of `events` differs from Node.js (and this causes some problems with `worker_threads`). So I will rewrite it.

2021-09-06 20:43 UTC, bartlomieju commented on node/worker_threads.ts
> +/// <reference lib="webworker"/>
@kitsonk could you please advice on this situation?

2021-10-10 13:07 UTC, bartlomieju commented
Ooops, looks like I borked the merge.

2021-10-10 13:08 UTC, Mesteery commented
no worries, it's fixed

2022-01-29 15:30 UTC, guybedford commented
It's a shame this one got derailed, the PR seemed to be very close!

2022-01-29 15:55 UTC, bartlomieju commented
@guybedford this PR is more or less complete, however there's still problem with TS types. I wonder if we should maybe skip typings completely for the time being and just land it.

2022-02-01 10:03 UTC, kt3k commented
I think I managed to fix type errors. PTAL @bartlomieju @kitsonk

2022-02-01 10:43 UTC, bartlomieju commented
@kt3k this seems fine to me, but I will let @kitsonk take a look before landing.

2022-02-04 11:19 UTC, bartlomieju commented
This is a blocker for `parcel`, so I'm going to land this PR tonight.

2022-02-04 12:10 UTC, littledivy requested changes
`require` and compat APIs are not available to workers. Can we please add that?

2022-02-06 11:55 UTC, Mesteery commented
> require and compat APIs are not available to workers. Can we please add that? EDIT: Needs support in CLI

Sorry but I am not familiar with Deno. What do you mean by that?

2022-02-06 17:57 UTC, bartlomieju commented
> > require and compat APIs are not available to workers. Can we please add that? EDIT: Needs support in CLI
> 
> Sorry but I am not familiar with Deno. What do you mean by that?

This is something I will work on, currently worker API doesn't respect "compat" mode and doesn't add required globals.

2022-02-11 13:57 UTC, bartlomieju commented on node/worker_threads.ts
> +  );
This line causes following error to be raised:
```
error: Uncaught (in worker "") Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.
error: Uncaught (in promise) Error: Unhandled error. ('Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.')
    const err = new ERR_UNHANDLED_ERROR(stringifiedEr);
```

2022-03-08 01:39 UTC, bartlomieju commented
After a lot back and forth I found the root problem of the implementation of this PR. Currently tests fails with "Module execution is still pending but there are no pending ops..." suggesting that there's a promise that never resolves. I found that this is caused by `parentHandle` (which is somewhat an alias of `self`) is not actually an `EventEmitter` instance and so events are not properly dispatched. I'm not sure how to solve this problem, if I understood correctly we would have to make `self` (in the worker context) an instance of `EventEmitter` but I'm unsure how this could be achieved. Any ideas are welcome.

Alternatively we would have apply a lot of code from `EventEmitter` manually to copy the behavior (though it still might not be enough due to `instanceof` checks)

2022-03-22 13:01 UTC, bartlomieju approved these changes
LGTM, thanks for finishing this @kt3k. And thank you to @Mesteery sorry it took so long to land this!

2022-03-22 13:05 UTC, littledivy approved these changes
:shipit:

2022-03-22 14:04 UTC, kt3k approved these changes
@Mesteery Thank you for your initial work!

2022-03-22 14:04 UTC, merged