fix(crypto): Browser compatibility
denoland/deno_std pull request #2141
Opened 2022-04-23 06:17 UTC by YXL76

Chrome disables `WebAssembly.Module` and `WebAssembly.Instance` for buffers larger than 4 KB.

2022-04-25 20:15 UTC, bartlomieju requested changes
@YXL76 thank you for the PR, please explain the changes you did. There are no changes in tests, so I'm not sure what's being fixed here.

2022-04-26 02:00 UTC, YXL76 commented
As what I say, this is for Chrome, which disables synchronous compilation and instantiation of  large buffer on the main thread. I just convert `WebAssembly.Module` and `WebAssembly.Instance`   to their async version, which follows the error message.

> Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.

2022-04-26 04:20 UTC, kt3k commented
Side note: A little concern about this change is that now this module can't be converted to CJS by [dnt](https://github.com/denoland/dnt) because of the use of top-level-await. But I think that's enough minor thing (dnt users can still target ESM, also they can provide workaround in some ways)

2022-04-26 04:20 UTC, kt3k approved these changes

2022-11-07 07:35 UTC, kt3k commented
Closing as it's stale. Also this work now needs to be done in https://github.com/denoland/wasmbuild

2022-11-07 07:35 UTC, closed without merging