feat(node): Add support for os.uptime
denoland/deno_std pull request #3052
Opened 2022-12-24 13:31 UTC by kamilogorek

Dependent on https://github.com/denoland/deno/pull/17179

A part of https://github.com/denoland/deno_std/issues/1436
This will also allow for out-of-the-box support for `npm:@sentry/node`, ref: https://github.com/getsentry/sentry-javascript/issues/3009#issuecomment-1364503874

2022-12-25 05:49 UTC, lino-levan commented
LGTM. Nice work!

2022-12-27 17:18 UTC, lino-levan commented
@kamilogorek this should probably be un-drafted given that https://github.com/denoland/deno/pull/17179 got merged?

2022-12-28 04:55 UTC, kt3k commented
@bartlomieju Do you think it's ok to require `--unstable` for `os.uptime` usage in npm compat? Or should we use `Deno[Deno.internal].nodeUnstable` namespace for bypassing `--unstable` requirement? (like https://github.com/denoland/deno_std/pull/2839)

2022-12-28 09:06 UTC, bartlomieju commented
> @bartlomieju Do you think it's ok to require `--unstable` for `os.uptime` usage in npm compat? Or should we use `Deno[Deno.internal].nodeUnstable` namespace for bypassing `--unstable` requirement? (like #2839)

Ah, good point; I forgot about that. Yeah I think it would be preferable to avoid `--unstable` here. Should I open a PR to do that?

2022-12-28 14:08 UTC, kamilogorek commented
I believe there's no need to rerun the tests after internal changes, as they were tested in `denoland/deno` itself.

2022-12-28 16:26 UTC, bartlomieju requested changes

2022-12-28 16:26 UTC, bartlomieju commented on node/os.ts
> +  return Deno.osUptime();
Please add 
```
// @ts-ignore Deno[Deno.internal] is used on purpose here
const DenoOsUptime = Deno[Deno.internal]?.nodeUnstable?.osUptime || Deno.osUptime;
```
at the top of the file and use `DenoOsUptime()` here

2022-12-29 09:55 UTC, bartlomieju approved these changes
LGTM, thanks @kamilogorek

2022-12-29 09:55 UTC, merged