feat: add webgpu folder
denoland/deno_std pull request #3119
Opened 2023-01-16 05:26 UTC by crowlKats

2023-07-25 04:57 UTC, iuioiua commented
Is this still something you want to pursue, @crowlKats?

2023-10-09 04:43 UTC, iuioiua commented
@crowlKats, do you think we should close this for now since the WebGPU API is currently not supported? We could re-open this and #3036 once support has been re-added.

2023-10-09 05:14 UTC, crowlKats commented
@iuioiua i think webgpu coming back might be quite soon, so don't think it's necessary to close it

2023-12-11 00:36 UTC, iuioiua commented
@crowlKats, it looks like `create_capture.ts` and `describe_texture_format.ts` might need to be removed to get the first pass over the line. Can you please confirm?

2023-12-11 02:02 UTC, iuioiua requested changes
I'm not familiar with the WebGPU API, but from a layout and structure perspective, mostly LGTM! I think we just missing a couple of pieces of documentation, mostly examples.

2023-12-11 02:48 UTC, iuioiua commented on test.ts
Is this here on purpose?

2023-12-11 02:49 UTC, iuioiua requested changes

2023-12-11 02:49 UTC, iuioiua commented on webgpu/mod.ts
> +export * from "./describe_texture_format.ts";
```suggestion
```

2023-12-11 02:53 UTC, iuioiua approved these changes
LGTM! Niiiice. We should request review from someone who better knows the WebGPU API too.

2023-12-11 02:55 UTC, crowlKats commented
@iuioiua there is no one in the core team like that 😅

2023-12-11 03:00 UTC, iuioiua commented
Reviews from contributors are also welcome!

2023-12-11 04:06 UTC, iuioiua commented
Note to maintainers: only merge this right before the next release. CI will remain in a failed state until the next runtime release.

2023-12-11 14:00 UTC, kt3k commented
> Note to maintainers: only merge this right before the next release. CI will remain in a failed state until the next runtime release.

This is very tricky. [The current release flow](https://github.com/denoland/deno/blob/main/tools/release/release_doc_template.md) doesn't allow such thing because the next version of std needs to be released before the next version of CLI.

If we'd prefer to release this for the next version, maybe we should disable stable CI for a moment?

2023-12-11 14:59 UTC, load1n9 commented
LGTM nothing really needs to be changed atm

2023-12-11 15:01 UTC, crowlKats commented
Thanks for reviewing @load1n9

2023-12-12 04:13 UTC, iuioiua commented
PTAL @kt3k

2023-12-12 04:32 UTC, kt3k approved these changes
LGTM!

2023-12-12 04:33 UTC, merged