refactor(_util): remove `_util/os`
denoland/deno_std pull request #3564
Opened 2023-08-22 22:47 UTC by kt3k

We're trying to remove top-level `_util` module because it's inconvenient for publishing each submodule independently.

This PR removes `_util/os.ts` with below changes:
- Copies `_util/os.ts` to `path/_os.ts` as `path` uses all exported items of `_util/os.ts`
- Replaces other usages with `const isWindows = Deno.build.os === "windows"` because they only use `isWindows` and also those usages don't require browser compatibility

related #3563

2023-08-23 02:31 UTC, iuioiua requested changes

2023-08-23 02:31 UTC, iuioiua commented on path/glob.ts
> +import { isWindows, osType } from "./_os.ts";
```suggestion
import { isWindows, osType, type OSType } from "./_os.ts";
```

2023-08-25 09:00 UTC, bartlomieju approved these changes
LGTM

2023-08-25 09:02 UTC, iuioiua approved these changes

2023-08-25 09:07 UTC, merged