doc: improve dotenv config option description
denoland/deno_std pull request #3570
Opened 2023-08-23 13:39 UTC by cknight

The current description of the `restrictEnvAccessTo` is confusing and potentially misleading.  This PR attempts to simplify the description.

Example of behaviour:
```sh
#.env
HELLO=world
SOME=${A}
THING=${B}
```

```ts
//main.ts
import {load} from https://deno.land/std@0.199.0/dotenv/mod.ts
const env1 = await load({ restrictEnvAccessTo: ['A'] });  //.env only has access to A
console.log(env1);
const env2 = await load(); //.env has access to both A and B
console.log(env2);
```
and invoke with:
```sh
A=1 B=2 deno run -A main.ts
```

the output is:
```sh
{ HELLO: "world", SOME: "1", THING: "undefined" }
{ HELLO: "world", SOME: "1", THING: "2" }
```

2023-08-23 21:33 UTC, iuioiua requested changes

2023-08-23 21:33 UTC, iuioiua commented on dotenv/mod.ts
> + * |restrictEnvAccessTo||Restrict which process env variables are accessible in the .env or .env.default files
```suggestion
 * |restrictEnvAccessTo||Restrict which process environment variables are accessible in the `.env` or `.env.default` files
```
Nit

2023-08-23 22:30 UTC, iuioiua approved these changes
Nice!

2023-08-24 04:01 UTC, kt3k approved these changes
Thanks!

2023-08-24 04:02 UTC, merged