BREAKING(fmt): rename stripColor to stripAnsiCode
denoland/deno_std pull request #3588
Opened 2023-08-30 20:10 UTC by lino-levan

Closes #3580

2023-08-30 22:49 UTC, iuioiua requested changes

2023-08-30 22:49 UTC, iuioiua commented on fmt/colors.ts
>  }
```suggestion
export const stripColor = stripAnsiCode;
```
Nit

2023-08-31 00:45 UTC, iuioiua approved these changes

2023-08-31 02:09 UTC, lino-levan commented
Another flaky test failure it appears

2023-08-31 05:21 UTC, kt3k approved these changes
LGTM. Thanks

2023-08-31 05:22 UTC, merged