Deprecate groupBy
denoland/deno_std pull request #3663
Opened 2023-09-21 03:02 UTC by NotWoods

`groupBy` can be replaced by `Object.groupBy` in Deno 1.37. Creating this as a draft for now because the TypeScript lib isn't updated, but running this without typechecking passes fine.

2023-09-23 17:51 UTC, lino-levan commented
Related to #3594.

2023-11-02 03:43 UTC, iuioiua requested changes

2023-11-02 03:43 UTC, iuioiua commented on collections/group_by.ts
> + * @deprecated Use `Object.groupBy` instead.
```suggestion
 * @deprecated (will be removed in 0.207.0) Use {@linkcode Object.groupBy} instead.
```

2023-11-02 03:48 UTC, iuioiua approved these changes
This change looks reasonable and good to me. Thanks!

2023-11-02 06:32 UTC, kt3k commented
Deprecation makes sense to me, but safari still doesn't support this according to MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy

I'm afraid we might get similar reaction to the case of `readableStreamFromIterable()` https://github.com/denoland/deno_std/pull/3579#issuecomment-1700637852

2023-11-02 06:55 UTC, lino-levan commented
Not sure about this. I'm still considering `std/shim` or `std/ponyfill` or something.

2023-11-22 08:31 UTC, kt3k commented
We updated the deprecation policy in https://github.com/denoland/deno_std/pull/3807

Now we recommend the users to pin the URL to the old std version if they still need them.

2023-11-22 08:31 UTC, kt3k approved these changes
LGTM

2023-11-22 08:33 UTC, merged