Optimizing Performance and Enhancing Code Clarity with Asynchronous Function Parallelism Using `Promise.all` 🚀
denoland/deno_std pull request #3683
Opened 2023-09-30 17:41 UTC by sanjaiyan-dev

2023-09-30 17:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=3683) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=3683) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=3683) it.</sub>

2023-09-30 23:49 UTC, aapoalas commented on fs/copy.ts
> +  let promisesCopyAsyncFunctions: Promise<void>[] = [];
**nitpick:** Use `const`

2023-10-02 01:46 UTC, kt3k commented on fs/empty_dir.ts
> +    items.length = 0;
nit: Is this necessary?

2023-10-02 01:53 UTC, kt3k commented
Looks good to me. Can you fix CI errors (run `deno fmt` and `deno lint`) and address nitpick comments?

2023-10-02 05:16 UTC, sanjaiyan-dev commented
> Looks good to me. Can you fix CI errors (run `deno fmt` and `deno lint`) and address nitpick comments?

Okay 🫱🏼‍🫲🏾

2023-10-08 19:00 UTC, sanjaiyan-dev commented
Done :)

2023-10-09 04:32 UTC, iuioiua reviewed
Just a couple of nits.

2023-10-09 04:32 UTC, iuioiua commented on fs/copy.ts
> +  const promisesCopyAsyncFunctions: Promise<void>[] = [];
```suggestion
  const promises = [];
```
I feel like this would've been sufficient.

2023-10-09 04:32 UTC, iuioiua commented on http/cookie_map.ts
> +    const promisesCookiesKeys: Promise<this>[] = [];
```suggestion
    const promises = [];
```
Ditto. This, I think, would've sufficed.

2023-10-09 04:45 UTC, sanjaiyan-dev commented
> Just a couple of nits.

Done 👍🏽

2023-10-09 04:48 UTC, iuioiua requested changes

2023-10-09 04:48 UTC, iuioiua commented on fs/copy.ts
> +      promisesCopyAsyncFunctions.push(copySymLink(srcPath, destPath, options));
```suggestion
      promises.push(copySymLink(srcPath, destPath, options));
```
Sorry, I should've mentioned that these also need to be renamed.

2023-10-09 04:48 UTC, iuioiua commented on fs/copy.ts
> +      promisesCopyAsyncFunctions.push(copyDir(srcPath, destPath, options));
```suggestion
      promises.push(copyDir(srcPath, destPath, options));
```
Ditto

2023-10-09 04:48 UTC, iuioiua commented on fs/copy.ts
> +      promisesCopyAsyncFunctions.push(copyFile(srcPath, destPath, options));
```suggestion
      promises.push(copyFile(srcPath, destPath, options));
```

2023-10-09 04:48 UTC, iuioiua commented on fs/empty_dir.ts
> +    items.length = 0;
Yeah, this doesn't seem necessary.

2023-10-09 04:48 UTC, iuioiua commented on fs/copy.ts
> +  await Promise.all(promisesCopyAsyncFunctions);
```suggestion
  await Promise.all(promises);
```

2023-10-09 04:48 UTC, iuioiua commented on http/cookie_map.ts
> +      promisesCookiesKeys.push(this.set(key, null, options));
```suggestion
      promises.push(this.set(key, null, options));
```

2023-10-09 04:48 UTC, iuioiua commented on http/cookie_map.ts
> +    await Promise.all(promisesCookiesKeys);
```suggestion
    await Promise.all(promises);
```

2023-10-09 05:19 UTC, sanjaiyan-dev commented
Sorry, and fixed it 🤝 @iuioiua

2023-10-09 05:31 UTC, iuioiua commented on fs/empty_dir.ts
> +    items.length = 0;
@sanjaiyan-dev

2023-10-09 18:33 UTC, iuioiua approved these changes
LGTM 👍🏾

2023-10-09 18:34 UTC, sanjaiyan-dev commented
> LGTM 👍🏾

Tks 🤝

2023-10-09 18:35 UTC, iuioiua commented
Btw, I’d also change the title to something like “perf: use `Promise.all()`”

2023-10-11 15:58 UTC, sanjaiyan-dev commented
> Btw, I’d also change the title to something like “perf: use `Promise.all()`”
@iuioiua 
Hope current title is in correct format 🤞🏽

2023-10-12 06:15 UTC, kt3k approved these changes
LGTM. Thanks!

2023-10-12 06:16 UTC, merged

2023-10-12 13:59 UTC, sanjaiyan-dev commented
> LGTM. Thanks!

🤝 🤩