BREAKING(path): split up glob into multiple files
denoland/deno_std pull request #3711
Opened 2023-10-22 01:57 UTC by lino-levan

Closes https://github.com/denoland/deno_std/issues/3600

Please take a careful look, I might've missed something.

2023-10-22 03:42 UTC, lino-levan commented
Looks like several flaky tests :/

Any idea why these are happening now @iuioiua?

2023-10-22 04:24 UTC, iuioiua commented
I don’t know the fix. I’ve asked Leo if he has any ideas.

2023-10-24 02:48 UTC, iuioiua requested changes

2023-10-24 02:48 UTC, iuioiua commented on path/glob.ts
> +export const isGlob = _isGlob;
```suggestion
export {
  /**
   * @deprecated (will be removed in 0.215.0) Import from "std/path/windows/is_glob.ts"
   *
   * Test whether the given string is a glob
   */
  isGlob,
} from "./is_glob.ts";
```
I think this approach is cleaner. Ditto for the other instances.

2023-10-25 21:22 UTC, iuioiua commented on path/glob.ts
> +export const isGlob = _isGlob;
Yep 👍🏾

2023-10-26 00:12 UTC, iuioiua reviewed
None of these glob functions are platform-specific. Their implementations are identical and duplicated across both platforms. They should be split up at the top level of `std/path` but not in platform-specific folders. Am I missing something here?

2023-10-26 00:25 UTC, iuioiua commented
Oh, I see they use different `normalize()` functions... Nevermind. Please allow a little time for me to comb through this.

2023-11-01 06:59 UTC, kt3k approved these changes
LGTM

2023-11-02 04:32 UTC, iuioiua approved these changes
LGTM. However, there's some duplicated code between the two functions. E.g. `normalizeGlob()` are essentially the same on both platforms, except that they rely on different underlying `normalize()` and `SEP_PATTERN` symbols. Let's discuss options for making this better in an issue.

2023-11-02 05:39 UTC, kt3k commented
@lino-levan Thank you for your contribution!

2023-11-02 05:51 UTC, merged