chore: remove deprecated `BytesList` in `readDelim`
denoland/deno_std pull request #3726
Opened 2023-10-26 10:20 UTC by 0scvr

Removed use of deprecated `BytesList` in `readDelim` in favour of  `Uint8Array`.

See #3718

2023-10-26 10:47 UTC, iuioiua commented
Hm, I would’ve thought `concat()` would be needed here. WDYT, @kt3k?

2023-10-28 12:37 UTC, iuioiua requested changes

2023-10-28 12:37 UTC, iuioiua commented on io/read_delim.ts
> +    chunks = new Uint8Array([...chunks, ...inspectArr.slice(0, result)]);
Let's use `concat()` here.

2023-10-28 15:39 UTC, 0scvr commented on io/read_delim.ts
> +    chunks = new Uint8Array([...chunks, ...inspectArr.slice(0, result)]);
Ah yes, concat would be a lot simpler

2023-10-28 21:18 UTC, iuioiua approved these changes
I made a tweak, and now, LGTM! Thank you.

2023-10-28 21:18 UTC, merged