chore(semver): add regexp capturing groups
denoland/deno_std pull request #3956
Opened 2023-12-13 21:32 UTC by timreichen

adds regexp capturing groups for more clarity.

2023-12-14 21:10 UTC, iuioiua requested changes

2023-12-14 21:10 UTC, iuioiua commented on semver/parse.ts
> +  if (!groups) throw new TypeError(`Invalid Version: ${version}`);
```suggestion
  const groups = version.match(FULL_REGEXP)?.groups;
  if (!groups) throw new TypeError(`Invalid Version: ${version}`);
```

2023-12-14 21:10 UTC, iuioiua commented on semver/parse_range.ts
> +      // range = range.replace(HYPHENRANGE_REGEXP, hyphenReplace);
```suggestion
```

2023-12-14 21:11 UTC, iuioiua requested changes
Nice improvement in readability. Few nits.

2023-12-14 22:23 UTC, iuioiua approved these changes
LGTM. Nice!

2023-12-14 22:23 UTC, iuioiua approved these changes
LGTM. Nice!

2023-12-18 08:12 UTC, kt3k approved these changes
LGTM

2023-12-18 08:12 UTC, merged