chore(semver): rename isSemVerRange and isSemVerComparator
denoland/deno_std pull request #3957
Opened 2023-12-13 21:41 UTC by timreichen

renames
`isSemVerRange()` => `isRange()`
`isSemVerComparator()` => `isComparator()`
`SemVerRange` => `Range`
`SemVerComparator` => `Comparator`
All old functions and interfaces are deprecated.

2023-12-14 01:47 UTC, iuioiua requested changes

2023-12-14 01:47 UTC, iuioiua commented on semver/is_semver_comparator_test.ts
I think this file should be `is_comparator_test.ts`.

2023-12-14 01:47 UTC, iuioiua commented on semver/is_semver_range.ts
> + * @deprecated (will be removed in 0.211.0) use `Range` instead.
```suggestion
 * @deprecated (will be removed in 0.212.0) Use {@linkcode isRange} instead.
```

2023-12-14 01:47 UTC, iuioiua commented on semver/is_semver_comparator.ts
> + * @deprecated (will be removed in 0.211.0) use `isComparator` instead.
```suggestion
 * @deprecated (will be removed in 0.212.0) Use {@linkcode isComparator} instead.
```

2023-12-14 01:47 UTC, iuioiua commented on semver/types.ts
> + * @deprecated (will be removed in 0.211.0) use `Comparator` instead.
```suggestion
 * @deprecated (will be removed in 0.212.0) Use {@linkcode Comparator} instead.
```

2023-12-14 09:27 UTC, timreichen commented
@iuioiua Before merging: There is also an opportunity to simplify `Range` and lose the single `ranges` property:

before
```ts
export interface Range {
  // The outer array is OR while each inner array is AND
  ranges: SemVerRangeOr;
}
```
after
```ts
// The outer array is OR while each inner array is AND
export type Range = Comparator[][];
```
WDYT?

2023-12-14 19:57 UTC, timreichen commented on semver/is_semver_comparator_test.ts
Done

2023-12-14 21:06 UTC, iuioiua requested changes
Sorry, I missed a couple of nits.

2023-12-14 21:06 UTC, iuioiua commented on semver/is_semver_comparator.ts
>  }
```suggestion
export const isSemVerComparator = isComparator;
```
Sorry, should've spotted this earlier.

2023-12-14 21:06 UTC, iuioiua commented on semver/is_semver_range.ts
>  }
```suggestion
export const isSemVerRange = isRange;
```

2023-12-14 21:06 UTC, iuioiua requested changes
Sorry, I missed a couple of nits.

2023-12-14 22:11 UTC, timreichen commented
No problem.

> @iuioiua Before merging: There is also an opportunity to simplify `Range` and lose the single `ranges` property:
> 
> before
> 
> ```ts
> export interface Range {
>   // The outer array is OR while each inner array is AND
>   ranges: SemVerRangeOr;
> }
> ```
> 
> after
> 
> ```ts
> // The outer array is OR while each inner array is AND
> export type Range = Comparator[][];
> ```
> 
What is your opinion on this?

2023-12-14 22:37 UTC, timreichen commented
Actually, looking into Range a bit more, it seems that the current implementation is kinda strange.
It is defined like multiple segments on a line. Imo Range implies to be a single segment.

2023-12-14 22:55 UTC, iuioiua commented
Yeah, it is strange. I see repeated use of `range.ranges`. It should probably be just `ranges` (without the `ranges` property).

2023-12-14 23:24 UTC, timreichen commented
How about we redefine Range to `export type Range = Comparator[]` and remove one OR layer. The OR layer is based on `parseRange` implementation which can parse `range || range`, but  it should actually return Range[] instead of Range and be called `parseRanges` instead of `parseRange`.

2023-12-15 00:09 UTC, iuioiua commented
The first solution sounds better.

2023-12-15 01:16 UTC, timreichen commented
> Yeah, it is strange. I see repeated use of `range.ranges`. It should probably be just `ranges` (without the `ranges` property).

The more I investigate about the Range implementation, the more am I convinced that the two renames
- isSemVerRange() => isRange()
- SemVerRange => Range

are misleading.

Their actual definition of SemVerRange is not a single Range but an array of Ranges.
Instead of renaming Ranges, we should implement `Range` and also adjust the API functions to accept Range instead of Ranges. Basically all range* functions (`rangeFormat`, `rangeMin`, `rangeMax`, `rangeIntersects`, `minSatisfying`, `maxSatisfying`,  `testRange`, etc.) just loop over the Range array anyway. So instead I would suggest changing these to accept a single Range and get rid of all these loops. WDYT?

**Please do not merge** until this fundamental problem is solved.

2023-12-15 07:30 UTC, iuioiua commented
Are you able to open a new issue focusing on this weird nested range design? There may be a reason (or there may not be) for this design decision.

Either way, let's proceed with this PR as it focuses on removing the `SemVer` portion of these symbol names.

2023-12-15 08:07 UTC, timreichen commented
@iuioiua I will open a new issue for this. This misnomer is also present in the npm semver.  Even the bnf file https://github.com/npm/node-semver/blob/main/range.bnf calls it `range-set`.

Would you be ok if I reduced this PR to
- `isSemVerComparator()` => `isComparator()`
- `SemVerComparator` => `Comparator`

so it can be merged?
Else we potentially would need to re-deprecate the `Range` later again and wait a cycle until we can fix the problem.

2023-12-17 20:52 UTC, iuioiua commented
Yep, let's reduce the PR 👍🏾

2023-12-17 21:11 UTC, timreichen commented on semver/is_semver_comparator.ts
>  }
done

2023-12-17 21:14 UTC, timreichen commented
> Yep, let's reduce the PR 👍🏾

done

2023-12-17 21:14 UTC, iuioiua approved these changes
LGTM! Thanks! Let's see what Yoshiya thinks.

2023-12-18 11:14 UTC, kt3k approved these changes
LGTM

2023-12-18 18:10 UTC, merged