chore(semver): deprecate rcompare
denoland/deno_std pull request #3958
Opened 2023-12-13 21:58 UTC by timreichen

add deprecation notice to `rcompare`

2023-12-13 22:00 UTC, iuioiua requested changes

2023-12-13 22:00 UTC, iuioiua commented on semver/rcompare.ts
> + * @deprecated (will be removed in 0.211.0) use `compare` instead.
```suggestion
 * @deprecated (will be removed in 0.212.0) Use {@linkcode compare} instead.
```

2023-12-13 22:17 UTC, iuioiua approved these changes
LGTM

2023-12-14 03:35 UTC, kt3k approved these changes
LGTM

2023-12-14 03:38 UTC, merged