refactor(data_structures): format test names
denoland/deno_std pull request #3991
Opened 2023-12-18 17:02 UTC by timreichen

Ref: https://github.com/denoland/deno_std/issues/3754

2023-12-18 21:39 UTC, iuioiua requested changes
Again, the use of the word "checks" doesn't make much sense to me. Are you able to sweep through and tweak?

2023-12-18 21:39 UTC, iuioiua commented on data_structures/binary_heap_test.ts
> +Deno.test("BinaryHeap() checks ascend comparator", () => {
```suggestion
Deno.test("BinaryHeap() works with ascend comparator", () => {
```

2023-12-18 21:39 UTC, iuioiua commented on data_structures/binary_heap_test.ts
> +Deno.test("BinaryHeap() checks default descend comparator", () => {
```suggestion
Deno.test("BinaryHeap() works with default descend comparator", () => {
```

2023-12-22 04:53 UTC, iuioiua approved these changes
I've made some adjustments. Now, LGTM. Thank you.

2023-12-28 04:16 UTC, kt3k approved these changes
LGTM

2023-12-28 04:17 UTC, merged