deprecation(semver): deprecate `eq()`, `neq()`, `lt()`, `lte()`, `gt()` and `gte()`
denoland/deno_std pull request #4048
Opened 2024-01-02 00:22 UTC by timreichen

ref: https://github.com/denoland/deno_std/issues/3948#issuecomment-1873464725

- deprecates `eq()`, `neq()`, `lt()`, `lte()`, `gt()` and `gte()`
- adds common use cases to `compare()` jsdoc

2024-01-02 00:43 UTC, iuioiua requested changes
I agree with the overall idea of this PR. I have just a few nits.

It'd be good to hear other's opinions on this change.

2024-01-02 00:43 UTC, iuioiua commented on semver/eq.ts
> + * @deprecated (will be removed in 0.213.0) use {@linkcode compare} instead.
```suggestion
 * @deprecated (will be removed in 0.213.0) Use {@linkcode compare} instead.
```
Ditto for other instances.

2024-01-02 00:43 UTC, iuioiua commented on semver/eq.ts
> + * This is equal to `compare(s0, s1) === 0`
```suggestion
 * This is equal to `compare(s0, s1) === 0`.
```
Ditto for other instances.

2024-01-02 00:43 UTC, iuioiua commented on semver/compare_test.ts
> +});
This is the only test needed. It takes care of all of the other equality and inequality cases more precisely.

2024-01-02 11:41 UTC, kt3k commented
I'd prefer to keep these methods as they are easier to remember than the meaning of return values of `compare`

2024-01-04 00:29 UTC, timreichen commented
> I'd prefer to keep these methods as they are easier to remember than the meaning of return values of `compare`

Ok, I will close this in favour of another PR.

2024-01-04 00:29 UTC, closed without merging