deprecation(semver): `Comparator` overloads for `comparatorMin()` and `comparatorMax()`
denoland/deno_std pull request #4053
Opened 2024-01-02 03:07 UTC by timreichen

- adds `Comparator` overloads to `comparatorMin()` and `comparatorMax()`
- deprecates other overloads

Reason being that it is unintuitive to spread `Comparator` arguments over a comparator function.

2024-01-02 03:32 UTC, iuioiua requested changes

2024-01-02 03:32 UTC, iuioiua commented on semver/comparator_max.ts
> +export function comparatorMax(semver: SemVer, operator: Operator): SemVer;
We should still retain the documentation for this overload. Ditto for `comparatorMin()`.

2024-01-02 20:48 UTC, iuioiua approved these changes
LGTM. Let's see what Yoshiya thinks.

2024-01-08 03:21 UTC, kt3k commented
This doesn't make much sense to me as we are now discussing #4047. I think we should first settle on #4047

2024-01-08 23:44 UTC, iuioiua commented
Closing in favour of #4131. Thank you, Tim.

2024-01-08 23:44 UTC, closed without merging