refactor(cli): public `Spinner.message` property
denoland/deno_std pull request #4079
Opened 2024-01-03 14:53 UTC by timreichen

- makes `Spinner.message` property public

Reason: Allows to change message during active spinner.

Example:
```ts
import { Spinner } from "https://deno.land/std@$STD_VERSION/cli/spinner.ts";
import { delay } from "https://deno.land/std@$STD_VERSION/async/delay.ts";

const spinner = new Spinner( { message: "Loading..." });
spinner.start();
await delay(1000);
spinner.message = "Almost done..."
await delay(1000);
spinner.stop();
```

2024-01-03 21:16 UTC, iuioiua approved these changes
I like the idea of this. Thank you.

It does make me think that this same change could be applied to some of the other properties.

2024-01-03 23:29 UTC, timreichen commented
> I like the idea of this. Thank you.
> 
> It does make me think that this same change could be applied to some of the other properties.

Like `color` and `interval`?

2024-01-04 00:32 UTC, iuioiua commented
Yep 👍🏾

2024-01-04 00:34 UTC, timreichen commented
> Yep 👍🏾

Should that be part of this PR or a separate one?

2024-01-04 01:05 UTC, iuioiua commented
Let's have it part of this one.

2024-01-04 09:41 UTC, timreichen commented
Actually, `interval` might need special treatment, else a change won't do anything.

2024-01-04 09:56 UTC, timreichen commented
Ok, I updated the code so it works when changing `interval` and `color`.
While at it, I removed the obsolete `#active` prop and made some adjustments for better readability.

2024-01-04 11:04 UTC, iuioiua requested changes
Frankly, I don't get some of these changes. I didn't think making color and friends would introduce such logic.

Sorry to change my mind, but can we revert to focusing on making `Spinner.message` public? Sorry for my previous suggestion. We should always keep PRs focused.

2024-01-04 11:04 UTC, iuioiua commented on cli/spinner.ts
> +  #frameIndex = 0;
What's the purpose of this change?

2024-01-04 11:09 UTC, timreichen commented on cli/spinner.ts
> +  message?: string;
I put internal props `#spinner` and `#interval` on top and changeable props at after.

2024-01-04 11:18 UTC, timreichen commented
> Frankly, I don't get some of these changes. I didn't think making color and friends would introduce such logic.
> 
> Sorry to change my mind, but can we revert to focusing on making `Spinner.message` public? Sorry for my previous suggestion. We should always keep PRs focused.

Ok, I reverted the changes and will open other PRs for the `color` and `interval`. There are some catches to be aware of so it works as intended, so the changes are not just to remove the hash.

2024-01-04 11:21 UTC, timreichen commented on cli/spinner.ts
> +  }
because the actual value is determined by `COLORS[value]`

2024-01-04 11:37 UTC, iuioiua approved these changes
Nice! LGTM. Thank you.

2024-01-04 11:41 UTC, merged