deprecation(log): rename `warning()` to `warn()`
denoland/deno_std pull request #4117
Opened 2024-01-05 10:56 UTC by timreichen

ref: https://github.com/denoland/deno_std/issues/4099

2024-01-05 20:16 UTC, joehillen commented on log/test.ts
> +    WARNING: log.warn,
`WARNING` should be changed to `WARN`

2024-01-05 21:19 UTC, iuioiua requested changes
Nice to see this done! Few nits.

2024-01-05 21:19 UTC, iuioiua commented on log/logger.ts
>    warning<T>(msg: T extends GenericFunction ? never : T, ...args: unknown[]): T;
```suggestion
  /** @deprecated (will be removed after 0.214.0) Use {@linkcode warn} instead. */
  warning<T>(msg: T extends GenericFunction ? never : T, ...args: unknown[]): T;
```
So both overloads show as deprecated.

2024-01-05 21:19 UTC, iuioiua commented on log/logger.ts
>      return this.#_log(LogLevels.WARNING, msg, ...args);
```suggestion
    return this.#_log(LogLevels.WARN, msg, ...args);
```

2024-01-05 21:19 UTC, iuioiua commented on log/mod.ts
>  export function warning<T>(
```suggestion
/**
 * @deprecated (will be removed after 0.214.0) Use {@linkcode warn} instead.
 *
 * Log with warning level, using default logger.
 */
export function warning<T>(
```

2024-01-05 21:19 UTC, iuioiua commented on log/mod.ts
> + * rror level, using default logger. */
Please revert

2024-01-05 21:19 UTC, iuioiua commented on log/test.ts
> +    WARNING: log.warn,
I agree

2024-01-07 06:46 UTC, timreichen commented on log/test.ts
> +    WARNING: log.warn,
done

2024-01-07 06:46 UTC, timreichen commented on log/mod.ts
> + * rror level, using default logger. */
done

2024-01-07 23:37 UTC, iuioiua approved these changes
LGTM! Nice.

Am I correct in understanding that this change is non-breaking?

2024-01-08 03:52 UTC, kt3k commented
> Am I correct in understanding that this change is non-breaking?

Strictly speaking, if the users do any log analysis using `WARNING` symbol, then that analysis will break. Can we delay the change of output string from `WARNING` to `WARN` to the actual breaking version? (`after 0.214.0`)

2024-01-08 21:28 UTC, timreichen commented
> > Am I correct in understanding that this change is non-breaking?
> 
> Strictly speaking, if the users do any log analysis using `WARNING` symbol, then that analysis will break. Can we delay the change of output string from `WARNING` to `WARN` to the actual breaking version? (`after 0.214.0`)

Reverted

2024-01-09 02:03 UTC, kt3k commented
@timreichen I don't see well what part is reverted?

The below still seems printing `WARN hi`
```js
import * as log from "./log/mod.ts";
log.warning("hi");
```

2024-01-09 09:38 UTC, timreichen commented
> @timreichen I don't see well what part is reverted?
> 
> The below still seems printing `WARN hi`
> 
> ```js
> import * as log from "./log/mod.ts";
> log.warning("hi");
> ```

Sorry, seems like the commit wasn't pushed. Done now.

2024-01-09 10:00 UTC, kt3k approved these changes
LGTM

2024-01-11 01:36 UTC, iuioiua approved these changes
LGTM. Thank you.

2024-01-11 01:36 UTC, merged