fix(expect): fix the function signature of `toMatchObject` (#4190)
denoland/deno_std pull request #4202
Opened 2024-01-15 07:28 UTC by BlackGlory

Fix https://github.com/denoland/deno_std/issues/4190

2024-01-15 07:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=4202) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=4202) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=4202) it.</sub>

2024-01-15 07:50 UTC, iuioiua requested changes
Thanks for your contribution! Can you please run `deno fmt`?

2024-01-15 07:50 UTC, iuioiua commented on expect/_matchers.ts
> +  expected: Record<PropertyKey, unknown> | Array<Record<PropertyKey, unknown>>,
```suggestion
  expected: Record<PropertyKey, unknown> | Record<PropertyKey, unknown>[],
```
Nit

2024-01-15 22:09 UTC, iuioiua approved these changes
LGTM. Thank you. @kt3k, should we also update `assertObjectMatch()` in a similar way?

2024-01-15 22:09 UTC, merged

2024-01-16 02:04 UTC, kt3k commented
> LGTM. Thank you. @kt3k, should we also update assertObjectMatch() in a similar way?

I don't think so. `toMatchObject` needed to be aligned to jest, but `assertObjectMatch` doesn't need to be aligned to anything.