refactor(encoding): prepare for `noUncheckedIndexedAccess`
denoland/deno_std pull request #4275
Opened 2024-02-04 14:43 UTC by eryue0220

Ref: #4040

2024-02-04 21:43 UTC, iuioiua requested changes
The aim of these PRs should be to fix any possible runtime bugs due to undeclared keys on objects. So, the changes should be justified based on runtime behaviour rather than just applying type castings to make the TypeScript checker happy.

For example, there should be a justification behind each time a non-null assertion is used. Comments on these changes would also help us (the maintainers) understand the reasons behind them.

Can you review this and related PRs and let us know once they're ready? If you'd like a guide on how these PRs should be approached, PTAL at previously merged ones by @syhol, who provides justifications behind changes: https://github.com/denoland/deno_std/pulls?q=is%3Apr+author%3Asyhol+is%3Aclosed+noUncheckedIndexedAccess

2024-02-04 21:43 UTC, iuioiua commented on encoding/ascii85_test.ts
> +        decodeAscii85(input as string),
This change is unnecessary if the `tests` variable is declared using `as const` (`const` assertion). This fact should be checked whenever a non-changing variable is used.

2024-02-05 09:12 UTC, eryue0220 commented on encoding/ascii85.ts
> +      output = output.map((val) => rfc1924[val.charCodeAt(0) - 33]) as string[];
Yeah, but I think it's better to express what type it's, if it just only one type, except `undefined`. And that's why I used `as` more than `!`.

2024-02-07 00:12 UTC, iuioiua commented on encoding/ascii85.ts
> +      output = output.map((val) => rfc1924[val.charCodeAt(0) - 33]) as string[];
Type-castings make more sense if the variable has more than one non-null type. E.g. `string | number | undefined`.

2024-02-15 21:41 UTC, iuioiua approved these changes
@eryue0220, I've gone ahead and applied the necessary tweaks. Now, this PR LGTM. @kt3k, PTAL.

2024-02-18 01:46 UTC, eryue0220 commented
@iuioiua

Thank you very much, I just finished my lunar new year vocation.

2024-02-24 20:24 UTC, merged