fix(datetime): allow passing options to `format()`
denoland/deno_std pull request #4285
Opened 2024-02-07 14:51 UTC by babiabeo

Fix: #4284

2024-02-07 22:32 UTC, iuioiua requested changes
Hey David, could we add the following to `datetime/format.ts` instead?
```ts
export interface FormatOptions {
  utc?: boolean;
}
```
We should also have accompanying documentation. WDYT?

2024-02-09 00:34 UTC, iuioiua commented on datetime/format.ts
> +/** The options used for formatting date in {@linkcode format}. */
```suggestion
/** Options for {@linkcode format}. */
```

2024-02-09 00:35 UTC, iuioiua approved these changes
LGTM! Thanks! I'll let Yoshiya review too.

2024-02-09 10:34 UTC, kt3k approved these changes
This addition makes sense to me. LGTM

2024-02-09 10:35 UTC, merged