build: update _ to - in workspace converter script
denoland/deno_std pull request #4357
Opened 2024-02-19 18:32 UTC by lucacasonato

2024-02-19 18:56 UTC, crowlKats approved these changes

2024-02-19 22:17 UTC, iuioiua requested changes
Is it intentional that folder names still contain underscores? I think we should change that too.

2024-02-20 09:04 UTC, lucacasonato commented
Yes this is intentional for the time being. This can be addressed in another follow up

2024-02-20 20:54 UTC, iuioiua approved these changes

2024-02-21 04:25 UTC, kt3k approved these changes

2024-02-21 12:43 UTC, merged