refactor(io): format test names
denoland/deno_std pull request #4413
Opened 2024-02-28 19:18 UTC by javihernant

ref #3754

2024-02-28 19:31 UTC, javihernant commented
The approach I am following is, I am trying to get a general idea of what the test is doing and then try to come up with an appropriate name. That is if I feel like the current title is not clear enough. However, I feel like I may have made some mistakes, so maybe it would be good if someone could check. Also, is it neccessary to include the function's name that is being tested. Some of the current title just explain what is going on without using the actual name of the function. And, there are still 19 test files left, each with several tests inside, so maybe this could be done by more people.

2024-02-28 20:35 UTC, timreichen commented on io/buf_reader_test.ts
> +Deno.test("BufReader fails reading with full buffer", async function () {
```suggestion
Deno.test("BufReader throws if reading with full buffer", async function () {
```

2024-02-28 20:37 UTC, timreichen commented on io/buf_reader_test.ts
> +Deno.test("readFull() fails if array length is too big", async function () {
dito

2024-02-28 20:37 UTC, timreichen commented on io/buf_reader_test.ts
> +Deno.test("readLine() fails with BadResource", async () => {
dito

2024-02-28 20:38 UTC, timreichen commented on io/buffer_test.ts
> +Deno.test("Buffer basic operations", async () => {
```suggestion
Deno.test("Buffer handles basic operations", async () => {
```

2024-02-28 20:38 UTC, timreichen commented on io/buffer_test.ts
> +Deno.test("read() empty at eof", async () => {
```suggestion
Deno.test("read() handles empty at eof", async () => {
```

2024-02-28 20:38 UTC, timreichen commented on io/buffer_test.ts
> +Deno.test("write() large bytes", async () => {
```suggestion
Deno.test("write() handles large bytes", async () => {
```

2024-02-28 20:39 UTC, timreichen commented on io/buffer_test.ts
> +Deno.test("write() large bytes", async () => {
```suggestion
Deno.test("write() handles large bytes", async () => {
```

2024-02-28 20:39 UTC, timreichen commented on io/buffer_test.ts
> +Deno.test("Buffer capacity with preallocated slice", () => {
```suggestion
Deno.test("Buffer handles capacity with preallocated slice", () => {
```

2024-03-04 04:10 UTC, iuioiua commented
@javihernant, Tim's suggestions are correct. Can you please apply them?

2024-03-04 07:44 UTC, javihernant commented
Yea, sure!

2024-03-05 00:21 UTC, iuioiua requested changes
Sorry, there's actually a number of nits I missed in my previous comment.

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("read() handles empty at eof", async () => {
```suggestion
Deno.test("Buffer.read() handles empty at eof", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("write() handles large bytes", async () => {
```suggestion
Deno.test("Buffer.write() handles large bytes", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("grow() throws if growing beyond maximum size", async () => {
```suggestion
Deno.test("Buffer.grow() throws if growing beyond maximum size", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "writeSync() grows buffer to max capacity",
```suggestion
  name: "Buffer.writeSync() grows buffer to max capacity",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "readFrom() rejects if read max_size + 1",
```suggestion
  name: "Buffer.readFrom() rejects if read max_size + 1",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "readFromSync() throws if read max_size + 1",
```suggestion
  name: "Buffer.readFromSync() throws if read max_size + 1",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "readFromSync() reads close to max_size",
```suggestion
  name: "Buffer.readFromSync() reads close to max_size",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "readFrom() reads close to max_size",
```suggestion
  name: "Buffer.readFrom() reads close to max_size",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +  name: "readFrom() reads close to max_size with initial grow",
```suggestion
  name: "Buffer.readFrom() reads close to max_size with initial grow",
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("write() handles large bytes", async () => {
```suggestion
Deno.test("Buffer.write() handles large bytes", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("readFrom()", async () => {
```suggestion
Deno.test("Buffer.readFrom()", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("readFromSync()", async () => {
```suggestion
Deno.test("Buffer.readFromSync()", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("grow()", async () => {
```suggestion
Deno.test("Buffer.grow()", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("writeAllSync() and readFromSync()", () => {
```suggestion
Deno.test("Buffer.write() and Buffer.readFromSync()", () => {
```
Note: `writeAll()` is not a `Buffer` method.

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("bytes() with copy set to false", () => {
```suggestion
Deno.test("Buffer.bytes() with copy set to false", () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("bytes() with copy set to false after grow()", () => {
```suggestion
Deno.test("Buffer.bytes() with copy set to false after Buffer.grow()", () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_writer_test.ts
> +Deno.test("write() writes different number of bytes", async function () {
```suggestion
Deno.test("BufWriter.write()", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_writer_test.ts
> +Deno.test("writeSync()", function () {
```suggestion
Deno.test("BufWriter.writeSync()", function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readBytes() reads string from buffer", async function () {
```suggestion
Deno.test("BufReader.readBytes() reads string from buffer", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("BufReader throws when reading with full buffer", async function () {
```suggestion
Deno.test("BufReader.readSlice() throws when reading with full buffer", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readString()", async function () {
```suggestion
Deno.test("BufReader.readString()", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readFull() throws if array length is too big", async function () {
```suggestion
Deno.test("BufReader.readFull() throws if array length is too big", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("peek()", async function () {
```suggestion
Deno.test("BufReader.peek()", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readLine()", async function () {
```suggestion
Deno.test("BufReader.readLine()", async function () {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readLine() throws with BadResource", async () => {
```suggestion
Deno.test("BufReader.readLine() throws with BadResource", async () => {
```

2024-03-05 00:21 UTC, iuioiua commented on io/buf_reader_test.ts
> +Deno.test("readLine() fills a full buffer", async () => {
```suggestion
Deno.test("BufReader.readLine() fills a full buffer", async () => {
```

2024-03-05 08:38 UTC, javihernant commented
Okay, Iḿ changing them now!

2024-03-11 07:36 UTC, iuioiua commented
@javihernant, please resolve any conversations in the PR and mark as ready for review once ready.

2024-03-14 06:20 UTC, iuioiua commented on io/buffer_test.ts
> +Deno.test("new Buffer()", () => {
```suggestion
Deno.test("Buffer", () => {
```

2024-03-14 06:26 UTC, iuioiua approved these changes
LGTM. Thank you.

2024-03-14 06:26 UTC, merged