feat(expect): add expect.{closeTo, stringContaining, stringMatching}
denoland/deno_std pull request #4508
Opened 2024-03-20 15:23 UTC by babiabeo

This PR adds these following asymmetric matchers:

- [x] expect.closedTo
- [x] expect.stringContaining
- [x] expect.not.stringContaining
- [x] expect.stringMatching
- [x] expect.not.stringMatching

Ref: #3964

2024-03-24 22:27 UTC, iuioiua requested changes

2024-03-24 22:27 UTC, iuioiua commented on expect/mod.ts
> + * The uitlities are not yet fully supported:
```suggestion
 * The utilities are not yet fully supported:
```

2024-03-24 22:27 UTC, iuioiua commented on expect/mod.ts
> + *   - `expect.not.objectContaining`
This doesn't make sense. Within a list of symbols that are not fully supported, there's a list of symbols that are supported. Can you please correct and clarify?

2024-03-24 22:27 UTC, iuioiua commented on expect/mod.ts
> + *   - `expect.addSnapshotSerializer`
Ditto. This doesn't make sense for the same reason as the above list. Please correct and clarify.

2024-03-24 22:27 UTC, iuioiua commented on expect/_asymmetric_matchers.ts
> +export function stringContaining(str: string) {
Please don't forget to define explicit return types (except for `void` or `Promise<void>`). Ditto elsewhere.

2024-03-25 13:36 UTC, babiabeo commented
Let me know if these changes make sense to you. 👍

2024-03-26 02:57 UTC, kt3k approved these changes
LGTM. Nice work!

2024-03-26 02:57 UTC, merged