deprecation(expect): rename `addSnapshotSerializers` to `addSnapshotSerializer`
denoland/deno_std pull request #4582
Opened 2024-04-14 09:16 UTC by uki00a

This PR renames `expect.addSnapshotSerializers` to `expect.addSnapshotSerializer` to match Jest's naming.

2024-04-14 22:55 UTC, iuioiua requested changes
Good catch! Thank you.

2024-04-14 22:55 UTC, iuioiua commented on expect/expect.ts
> + * @deprecated (will be removed in 1.0.0) Use {@linkcode expect.addSnapshotSerializer} instead.
`std/expect` is unstable. Let's remove this in 0.226.0.

2024-04-15 06:25 UTC, kt3k approved these changes
LGTM. Thanks!

2024-04-15 06:38 UTC, iuioiua approved these changes
LGTM. Thank you.

2024-04-15 06:39 UTC, merged