feat(http): file_server prints local network address
denoland/deno_std pull request #4604
Opened 2024-04-17 13:34 UTC by kt3k

closes #4597

This PR updates `onListen` hook of file_server to show the local network IP address. The scripts shows 2 urls like the below:

```shellsession
$ deno run -A http/file_server.ts 
Serving static files!
local: http://localhost:4507
network: http://192.168.0.104:4507
```

Suggestions to the output format are welcome

---

Note: `npm:serve` chooses non internal IPv4 address as the network address. This implementation follows it. ref. https://github.com/vercel/serve/blob/1ea55b1b5004f468159b54775e4fb3090fedbb2b/source/utilities/http.ts#L40

Note: Deno's [NetworkInterfaceInfo](https://deno.land/api@v1.42.4?s=Deno.NetworkInterfaceInfo) object doesn't have `internal` field, but it's polyfilled as `address.startsWith("127")` in the node compat layer https://github.com/denoland/deno/blob/9acbf90b06bf79dd6e4cf2428b3566da009bed65/ext/node/polyfills/os.ts#L232-L234. This implementation follows it as well.

2024-04-17 13:41 UTC, kt3k commented
Side note: This will prints ip address that is not useful to the user in Deno Deploy like:

```
Serving static files!
local: http://localhost:80
network: http://10.0.0.10:80
```

2024-04-17 23:11 UTC, iuioiua requested changes
Can you please add a test?

> Side note: This will prints ip address that is not useful to the user in Deno Deploy like:
> 
> ```
> Serving static files!
> local: http://localhost:80
> network: http://10.0.0.10:80
> ```

This doesn't seem to be the case, as the functionality added in this PR is only accessible when running the script directly via `deno run -A jsr:@std/http/file-server` because we're using `import.meta.main`.

2024-04-17 23:11 UTC, iuioiua commented on http/file_server.ts
> +  function onListen({ port }: { port: number }) {
My suggested format (staying close to default behaviour).
```
Listening on:
- Local: http://localhost:4507
- Network: http://192.168.0.104:4507
```

2024-04-17 23:11 UTC, iuioiua commented on http/file_server.ts
> +  function onListen({ port }: { port: number }) {
We should also use the `hostname` property.

2024-04-18 05:10 UTC, kt3k commented
> This doesn't seem to be the case. The functionality added in this PR is only accessible when running the script directly via deno run -A jsr:@std/http/file-server because we're using import.meta.main.

file_server is often used as the entrypoint script in Deploy when serving static site. `import.meta.main` is true in that case. ref. https://github.com/search?q=path%3Adeploy.yml%20file_server.ts&type=code

We even optimize etag generation for Deno Deploy. https://github.com/denoland/deno_std/pull/3186

2024-04-18 05:13 UTC, kt3k commented
Now this prints:

```shellsession
$ deno run -A http/file_server.ts 
Listening on:
- local: http://localhost:4507
- network: http://192.168.79.163:4507
```

2024-04-18 07:09 UTC, iuioiua requested changes
Testing of this script can be done another time. I created #4605 to track.

2024-04-18 07:09 UTC, iuioiua commented on http/file_server.ts
> +    if (networkAddress) {
```suggestion
    if (networkAddress && DENO_DEPLOYMENT_ID === undefined) {
```
So nothing is printed in Deno Deploy.

2024-04-19 04:57 UTC, iuioiua requested changes

2024-04-19 04:57 UTC, iuioiua commented on http/file_server_test.ts
> +      "--config",
Reduces flakiness (ref #4168):
```suggestion
      "--config",
      "--no-lock",
```

2024-04-19 05:00 UTC, kt3k commented on http/file_server_test.ts
> +      "--config",
`--no-lock` is at the above

2024-04-20 23:04 UTC, iuioiua commented on http/file_server_test.ts
> +  )?.address;
It seems like this should be used as the implementation for `getNetworkAddress()`.

2024-04-20 23:04 UTC, iuioiua approved these changes

2024-04-22 05:25 UTC, merged