Split toml/test.ts into separate files
denoland/deno_std pull request #4616
Opened 2024-04-20 21:41 UTC by elizasorber

Handling issue #4593. Took tests from toml/test.ts and split into toml/parse_tests.ts and toml/stringify_tests.ts

2024-04-20 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=4616) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=4616) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=4616) it.</sub>

2024-04-20 22:41 UTC, iuioiua requested changes
Can you please run `deno fmt`?

2024-04-20 22:41 UTC, iuioiua commented on toml/stringify_tests.ts
> +import { stringify } from "./mod.ts";
```suggestion
import { stringify } from "./stringify.ts";
```

2024-04-20 22:41 UTC, iuioiua commented on toml/parse_test.ts
> +import { parse, stringify } from "./parse.ts";
```suggestion
import { parse, stringify } from "./mod.ts";
```

2024-04-23 00:11 UTC, iuioiua requested changes

2024-04-23 00:11 UTC, iuioiua commented on toml/stringify_tests.ts
Please rename to `stringify_test.ts`.

2024-04-23 01:56 UTC, iuioiua requested changes

2024-04-23 01:56 UTC, iuioiua commented on toml/stringify_test.ts
> +import { stringify } from "./stringify.js";
Just to clarify, this is a TypeScript codebase.
```suggestion
import { assertEquals, assertThrows } from "../assert/mod.ts";
import { stringify } from "./stringify.ts";
```

2024-04-23 02:18 UTC, iuioiua commented
Looking at the tests, it seems some of the expected values within tests have been modified. Can you please revert such changes? Please let me know if you need a hand with anything.

2024-04-23 23:49 UTC, elizasorber commented
So sorry about that. It looks like your auto formatting indented the multi line string comparison in the backticks in a few of the tests. Should be passing those 4 tests now. Lmk if there's anything else you need from me.

2024-04-24 00:03 UTC, iuioiua approved these changes

2024-04-24 00:05 UTC, iuioiua commented
Great work! Thank you for making your first contribution. If you'd like to help with anything else, please let us know, and we can figure it out.

2024-04-24 00:06 UTC, merged