docs(expect): document methods and add expects to attain full score in JSR
denoland/deno_std pull request #4836
Opened 2024-05-22 18:17 UTC by satyarohith

- **add docs for fn module**
- **add docs for expect module**

2024-05-22 18:18 UTC, satyarohith commented on expect/expect.ts
> +  });
Note: just format diff

2024-05-22 23:12 UTC, iuioiua requested changes
Can you please add `../expect/mod.ts` to the [doc checker](https://github.com/denoland/deno_std/blob/83991c738edc33dcc63a099f505781a6f01809df/_tools/check_docs.ts#L28)?

2024-05-23 06:17 UTC, kt3k commented on expect/expect.ts
> +// Copyright (c) Meta Platforms, Inc. and affiliates.
👍

2024-05-23 10:22 UTC, kt3k approved these changes
LGTM. Thanks, Satya!

2024-05-23 10:22 UTC, kt3k commented on expect/expect.ts
> + * @ts-
remove?
```suggestion
```

2024-05-23 11:20 UTC, merged