replaced public and private access modifiers #5066
denoland/deno_std pull request #5077
Opened 2024-06-18 12:45 UTC by MadGanGithub

Fixes:
Removed public keyword
Added separate declaration and constructor assignment

Replaced private key with # keyword

2024-06-18 12:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=5077) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=5077) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=5077) it.</sub>

2024-06-18 21:22 UTC, iuioiua requested changes
It looks mostly good. There are a few nits that need to be addressed. Can you please run `deno fmt` to format the code?

2024-06-18 21:22 UTC, iuioiua commented on io/_test_common.ts
> +  constructor(bytes: Uint8Array = new Uint8Array(0)) {
Nit: the type can be inferred from the variable's default value. Type annotation is not needed.
```suggestion
  constructor(bytes = new Uint8Array(0)) {
```

2024-06-18 21:22 UTC, iuioiua commented on io/buf_reader.ts
> +  // #lastCharSize: number;
Nit: these aren't used. Safe to remove.
```suggestion
```

2024-06-18 21:22 UTC, iuioiua commented on io/string_writer.ts
> +  constructor(base: string = "") {
Ditto. Type annotation not needed.
```suggestion
  constructor(base = "") {
```

2024-06-18 21:22 UTC, iuioiua commented on yaml/_error.ts
> +  override toString(_compact: boolean): string {
Nit: let's remove this variable since it's not used.
```suggestion
  override toString(): string {
```

2024-06-18 21:22 UTC, iuioiua commented on yaml/_loader/loader_state.ts
> +    input: string,
I believe we need to define `this.input` to fix test failures.

2024-06-19 02:13 UTC, kt3k commented
Also please sign the CLA from the above @CLAassistant's comment.

2024-06-21 04:13 UTC, iuioiua approved these changes
I've taken the liberty of formatting and applying the suggested changes to take this over the line. Thank you for your contribution.

2024-06-21 04:13 UTC, merged