refactor(http): remove dead code and improve UserAgent testing
denoland/deno_std pull request #5120
Opened 2024-06-24 10:37 UTC by kt3k

This PR removes some dead code and improves typings in `http/user_agent.ts`, and also adds test cases which exercise uncovered lines.

towards #3713

2024-06-24 10:38 UTC, kt3k commented on http/user_agent.ts
> -  }
`str1` is always string with all `has` usages. This if-block is dead code.

2024-06-24 10:40 UTC, kt3k commented on http/user_agent.ts
> -              }
If `processor` has 4 elements, the 4th element needs to be a function by its typing. So this if-block does nothing.

2024-06-24 10:41 UTC, kt3k commented on http/user_agent.ts
> -          const match = matches[++k]!;
There were cases where `match` is actually `undefined`. So appending `!` here is not ideal.

2024-06-24 10:46 UTC, iuioiua requested changes
Few nits

2024-06-24 10:46 UTC, iuioiua commented on http/user_agent.ts
>    return lowerize(str2).indexOf(lowerize(str1)) !== -1;
How about `.includes()`?

2024-06-24 10:46 UTC, iuioiua commented on http/user_agent.ts
Can we remove `lowerize()` and `trim()`? Are there any others we can remove?

2024-06-24 11:23 UTC, kt3k commented on http/user_agent.ts
lowerize and trim is used as `ProcessingFn` in processors. I think it's difficult to remove them

2024-06-25 06:18 UTC, iuioiua approved these changes

2024-06-25 06:23 UTC, merged